name: Trip Planning Example

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'examples/trip-planning-example/**'
  pull_request:
    paths:
      - 'examples/trip-planning-example/**'

env:
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: 'corretto'

jobs:
  app-compilation:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Configure Git
        run: |
          git config --global core.autocrlf input
      - uses: actions/checkout@v6
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Assemble
        working-directory: ./examples/trip-planning-example
        run: ./gradlew assemble

      - name: ktlintCheck
        working-directory: ./examples/trip-planning-example
        run: ./gradlew ktlintCheck
